# these come from spark-operator chart in https://github.com/kubeflow/spark-operator/blob/master/charts/spark-operator-chart/values.yaml
spark-operator:
  spark:
    jobNamespaces: null
    serviceAccount:
      create: true
      name: ""
      annotations: {}
      automountServiceAccountToken: true
    rbac:
      create: true
      annotations: {}

spark:
  namespace: default
  type: Python
  pythonVersion: null # "3"
  image:
    repository: spark
    tag: 3.5.3
  mainApplicationFile: main.py
  volumes: []
  driver:
    labels: {}
    annotations: {}
    env: []
    volumeMounts: []
    affinity: {}
    tolerations: []
    resources: {}
  executor:
    labels: {}
    annotations: {}
    volumeMounts: []
    env: []
    affinity: {}
    tolerations: []
    resources: {}
  dynamicAllocation:
    enabled: false
    initialExecutors: null
    minExecutors: null
    maxExecutors: null
    shuffleTrackingTimeout: null
  deps:
    jars: []
    files: []
    pyFiles: []
    packages: []
    excludePackages: []
    repositories: []
    archives: []
    pypi_packages: ["pyspark==3.5.5"]

pyspark_dep_manager:
  image:
    repository: ghcr.io/neuro-inc/pyspark-dep-manager
    tag: latest
  labels: {}
  annotations: {}
  add_test_volumes: true
  volumes:
    - name: deps-export
      hostPath: 
        path: /host/deps
      # emptyDir: {}
  volumeMounts:
    - name: deps-export
      mountPath: /mnt/export