name: CI

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
    branches: [master]

jobs:
  test:
    name: All checks are passed
    uses: ./.github/workflows/test.yaml
    secrets: inherit

  pull_request:
    name: Release PR image
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
      - name: Purge old artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ github.token }}
          expire-in: 30mins
      - name: Login to ghcr.io
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/neuro-inc/pyspark-dep-manager
          tags: |
            type=ref,event=pr
      - name: Build Docker image
        run: make build-image-pydeps
      - name: Release branch image
        run: |
          export IMAGE_REF=${{ steps.meta.outputs.tags }}
          make push-image-pydeps
  release:
    name: Release image
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master')
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
      - name: Purge old artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ github.token }}
          expire-in: 30mins
      - name: Login to ghcr.io
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build Docker image
        run: make build-image-pydeps
      - name: Release development image
        run: |
          export HOOK_IMAGE_TAG=development
          make push-image-pydeps
      - name: Release production image
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          export HOOK_IMAGE_TAG=${GITHUB_REF#refs/tags/v}
          make push-image-pydeps

          export HOOK_IMAGE_TAG=latest
          make push-image-pydeps

  release-hook-image:
    name: Release hook image
    runs-on: ubuntu-latest
    needs: test
    if: (
      (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'))
      )
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
      - name: Set APP_HOOK_IMAGE_TAG
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BRANCH_NAME=${{ github.head_ref }}
            export APP_HOOK_IMAGE_TAG=$(echo "${BRANCH_NAME}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_.-]/-/g')
          elif [ "${{ github.ref }}" = "refs/heads/master" ]; then
            export APP_HOOK_IMAGE_TAG=apolo
          else
            export APP_HOOK_IMAGE_TAG=${GITHUB_REF#refs/tags/}
          fi
          echo "APP_HOOK_IMAGE_TAG=${APP_HOOK_IMAGE_TAG}" >> $GITHUB_ENV
      - name: Login to ghcr.io
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build image
        run: |
          export HOOK_IMAGE_TAG=${{ env.APP_HOOK_IMAGE_TAG }}
          make build-hook-image
      - name: Release branch image
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        run: |
          BRANCH_NAME=${{ github.head_ref }}
          # Convert to lowercase, replace anything not a-z0-9_.- with '-'
          export HOOK_IMAGE_TAG=$(echo "${BRANCH_NAME}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_.-]/-/g')
          make push-hook-image
      - name: Release development image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          export HOOK_IMAGE_TAG=apolo
          make push-hook-image
      - name: Release prod image
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          export HOOK_IMAGE_TAG=${GITHUB_REF#refs/tags/}
          make push-hook-image
